image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: clone

stages:
  - build
  # - deploy

build_container:
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  tags:
    - home
  when: manual

deploy_rak8s:
  stage: deploy
  image: $CI_REGISTRY_IMAGE:latest
  script:
    - echo "hello world"
    - ansible --version
  tags:
    - home
